# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x08msk_test\"\xb7\x01\n\tUserEvent\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x33\n\x08metadata\x18\x05 \x03(\x0b\x32!.msk_test.UserEvent.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa4\x01\n\nOrderEvent\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\"\n\x05items\x18\x03 \x03(\x0b\x32\x13.msk_test.OrderItem\x12\x14\n\x0ctotal_amount\x18\x04 \x01(\x01\x12%\n\x06status\x18\x05 \x01(\x0e\x32\x15.msk_test.OrderStatus\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\"V\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01*T\n\x0bOrderStatus\x12\x0b\n\x07PENDING\x10\x00\x12\r\n\tCONFIRMED\x10\x01\x12\x0b\n\x07SHIPPED\x10\x02\x12\r\n\tDELIVERED\x10\x03\x12\r\n\tCANCELLED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USEREVENT_METADATAENTRY']._loaded_options = None
  _globals['_USEREVENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ORDERSTATUS']._serialized_start=468
  _globals['_ORDERSTATUS']._serialized_end=552
  _globals['_USEREVENT']._serialized_start=28
  _globals['_USEREVENT']._serialized_end=211
  _globals['_USEREVENT_METADATAENTRY']._serialized_start=164
  _globals['_USEREVENT_METADATAENTRY']._serialized_end=211
  _globals['_ORDEREVENT']._serialized_start=214
  _globals['_ORDEREVENT']._serialized_end=378
  _globals['_ORDERITEM']._serialized_start=380
  _globals['_ORDERITEM']._serialized_end=466
# @@protoc_insertion_point(module_scope)
